### ISSUE TITLE
H5微信支付后没有进行支付是否成功的判断

### ISSUE THREAD

**Issue by magicsleep** [froger-me/wp-weixin#15]
您好，感谢您提供的免费插件，我再使用过程中发现H5进行微信支付时候，如果微信端没有支付，再回到H5，插件并没有根据是否支付成功显示出相应的页面，也没有地方进行相关的配置，这样的话，很容易对终端客户造成一个误解，以为已经支付成功了。

**Comment by froger-me** [comment]
Hello and thank you for your interest in WP Weixin and its companion plugins!

I am not sure how to replicate the issue, it may be theme specific or related to another plugin: here are the steps I took with the understanding I had of your case, all in a mobile browser (not WeChat), using the H5 method.

1 - checkout page ; click on pay with WeChatPay
![1](https://user-images.githubusercontent.com/3622456/75766561-52850a80-5d7c-11ea-8017-17fcd45c55ae.png)

2 - on the order summary page, click the button "Click to pay with WeChat"
![2](https://user-images.githubusercontent.com/3622456/75766662-7ba59b00-5d7c-11ea-84dd-d52abcdcaef4.png)

3 - when the WeChatPay window has opened, click the back button
![3](https://user-images.githubusercontent.com/3622456/75766731-924bf200-5d7c-11ea-8069-18d2454b64d0.png)

4 - When the modal window appear, click "Quit"
![4](https://user-images.githubusercontent.com/3622456/75766787-a859b280-5d7c-11ea-901c-acdeb6b96d24.png)

=> back to step 2, with the items still in the cart ; pressing the back button returns to the checkout page to maybe initiate payment with another method.

If the user **did** pay, the system will go to the thank you page and the order status will be change to "Pending Payment" (normal WooCommerce scenario). Then, asynchronously, WeChat will notify WooCommerce of the success or failure of the transaction and update the order status accordingly (it does not take long, but it's very often if not most of the times too late for the thank you page).
Because this is asynchronous, the thank you page cannot know the final status of the transaction at this point in most cases ; theme developers can change the content of that page with action and filter hooks to reflect the fact the transaction still needs approval, but that's specific behavior, not something WP Weixin or Woo WeChatPay should handle.

See `woocommerce/templates/checkout/thankyou.php` for more details - the same message is displayed unless the order status has been directly and synchronously set to `failed` ; in all other cases, the same text is displayed. And that's where code is needed.
A theme developper could either override the template entirely or edit `functions.php` to hook into `woocommerce_thankyou_order_received_text` filter, check the payment method, check the order status, and tell the customer with the text displayed that the order still needs approval from WeChat and that it will be updated in their account page shortly (with  link to the list of order, to make everything clear), if the order status is different from `processing`.

I hope I covered everything!
