### ISSUE TITLE
用户在第一次通过微信登录时完善邮箱的建议

### ISSUE THREAD

**Issue by leadroy** [froger-me/wp-weixin#19]
使用本系统已1个多月，功能和稳定性都达到了我们的预期。现在有一个问题一直困扰着我们，就是在用户通过微信浏览器第一次登录系统后系统会自动的创建一个以我们域名为后缀的邮箱，但是这个邮箱是不确定的。

如可以让用户在第一次登录时输入自己正确的邮箱用于完善个人资料是一个很好的选择。

我看了所有文档，没有找到可以实现这个功能的方法。

**Comment by froger-me** [comment]
Hi @leadroy !
When the user logs in automatically with WeChat for the first time, it creates the user but no email information is available.
Because WordPress requires an email address, a default value is filled in by WP Weixin, using the OpenID of the user and the website's domain to make sure it's unique and not empty ; however, WP Weixin cannot take care of the logic behind completing the user information with the correct email because it completely depends on what the website uses for profiles.

For deeper integration with user profile information, it's up to the developer to include that logic in a plugin or theme, for example by hooking into `template_redirect` WordPress action, check the user email is equal to `[openid]@your-domain.tld` (getting the `[openid]` value with `wp_weixin_get_user_wechat_openid( $user_id )` function), and redirect to the user profile page (URL depending on what your site is using to manage user profiles) with a message to change the email address.
