### ISSUE TITLE
Can I push WooCommerce orders?

### ISSUE THREAD

**Issue by zhujitop** [froger-me/wp-weixin#22]
Can I push WooCommerce order notifications to my users?

**Comment by froger-me** [comment]
Hi @zhujitop !

Yes it is possible, and there are several ways for that:
- you use the WP Weixin API to develop a companion plugin handling payment and notifications
- you use [WeChat Payment gateway for WooCommerce: Woo WeChatPay](https://github.com/froger-me/woo-wechatpay) plugin to handle payment and develop a companion plugin with the WP Weixin API to send payment notifications
- you use a templated message properly configured in both WeChat backend and Woo WeChatPay settings (/wp-admin/admin.php?page=wc-settings&tab=checkout&section=wechatpay)

I hope this helps ; I'll close the issue because it's an open-ended question and this answer provides enough directions towards a solution; please note that achieving your goal would require some research, configuration, tests and possibly development.
