### ISSUE TITLE
Token keep renewing before expiry

### ISSUE THREAD

**Issue by xpsg** [froger-me/wp-weixin#4]
I installed this plugin recently and noted that my tokens are instantly expiring and renewed with every request. This has led to my account running out of tokens within a few hours of testing.

I decided to look through the code and noted that the code that checks the expiry of the token is using current_time(). I changed it to time() and realized that the token expiry check is now working as intended, which is to get a new token if the expiry is within 30 mins of expiry.

I have no idea if this "fix" will negatively impact the plugin so I am submitting this issue for further investigation.

File: wp-weixin/inc/class-wp-weixin-wechat-singleton.php
Line: 28
```
( current_time( 'timestamp' ) + 1800 ) >= absint( self::$wechat->getAccessTokenExpiry() ) ||
```
to
```
( time () + 1800 ) >= absint( self::$wechat->getAccessTokenExpiry() ) ||
```

**Comment by froger-me** [comment]
Hello @xpsg, thank you for opening this issue, and especially for the research and proposed snippet - that's really appreciated.

I had some unexpected results in the past using `time()` and made a (bad, I admit, as pointed out [here](https://core.trac.wordpress.org/ticket/40657)) habit of using `current_time( 'timestamp' )` instead.

I wonder if, in your case, it is because your server time is not consistent with the timezone set in WordPress - I am not saying your configuration is an issue (because as I said, I really should be using `time()` here), I am just trying to imagine where the effect could come from, since it's the first time it's been reported...

I'll update the code base shortly in any case, but in the meantime feel free to keep the edited code, or fiddle with the timezone in configs if that helps - and thanks again for reporting this.

**Comment by froger-me** [comment]
Hmmm, I'm actually thinking: if your timezone in WordPress is NOT Asia/Shanghai, then indeed it will become problematic, because the SDK is calculating the expiry with `time()`.
Because WP Weixin is designed to work with Mainland Official Accounts primarily, I made the wrong assumption it would not be an issue. 

```php
$this->access_token_expire = time() + $jsonArr['expires_in'];
```

**Comment by xpsg** [comment]
Thanks for the quick investigation 👍 
Anyway, I checked my server timezone against WordPress config. They are the same =) 
Interestingly I am also in a +8 timezone(Server Timezone: Asia/Singapore)

**Comment by froger-me** [comment]
Code committed - closing

**Comment by froger-me** [comment]
@xpsg 
BTW, please don't hesitate to keep me updated in case of issue, and feel free to [leave a review](https://wordpress.org/support/plugin/wp-weixin/reviews)
